### ISSUE TITLE
Use <ext_name>.build_native.yaml to define extensions

### ISSUE THREAD

**Issue by thosakwe** [thosakwe/build_native#4]
In `sample_extension.build_native.yaml`:

```yaml
flags:
  - "-O2"
link:
  - sample_extension.o
```

Optionally, in `sample_extension.macos.build_native.yaml`:

```yaml
define:
  APPLE:
```
