### ISSUE TITLE
Allow including external projects?

### ISSUE THREAD

**Issue by thosakwe** [thosakwe/build_native#5]
i.e. for `ExternalProject`

**Comment by thosakwe** [comment]
To require an archive from the Internet:

```yaml
third_party:
  curl:
    url: https://curl.haxx.se/download/curl-7.60.0.zip
    url: https://curl.haxx.se/download/curl-7.60.0.tar
    url: https://curl.haxx.se/download/curl-7.60.0.tar.xz
    url: https://curl.haxx.se/download/curl-7.60.0.tar.gz
    url: https://curl.haxx.se/download/curl-7.60.0.tar.bz2
    md5: "some-hash-here" # Only if you intend to validate the file
```
